/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adt.aabernathypaper;

import org.junit.Test;

import adt.aabernathypaper.AabernathyPaper;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void sanityCheck() {
        assertEquals("Arithmetic suggests that 2 + 2 should equal 4", 4, 2 + 2, 0);
    }
}
