/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adt.aabernathypaper;

import org.bukkit.block.Block;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.Item;
import org.bukkit.event.EventHandler;
import org.bukkit.event.block.BlockDropItemEvent;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

import io.papermc.paper.event.block.BlockBreakBlockEvent;

public class AabernathyPaper extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
        saveDefaultConfig();
    }

    @Override
    public void onDisable() {
    }

    public ConfigurationSection econGetItemDefiniton(String name) {
        return getConfig()
            .getConfigurationSection("dynamic_econ")
            .getConfigurationSection(name);
    }

    public Double econGetItemWeight(String name) {
        return econGetItemDefiniton(name)
            .getDouble("weight_offset");
    }

    public Boolean econItemDefined(String name) {
        return getConfig()
            .getConfigurationSection("dynamic_econ")
            .contains(name);
    }

    public Boolean econItemIsRoot(String name) {
        return econGetItemDefiniton(name)
            .getBoolean("root_item");
    }

    @EventHandler
    public void handleBlockBroken(BlockBreakBlockEvent event) {
        Block block = event.getBlock();

        if (block.getType().isInteractable())
            return;
    }

    @EventHandler
    public void handleOnItemDrop(BlockDropItemEvent event) {
        String itemName;

        for (Item item : event.getItems()) {
            itemName = item
                .getName()
                .toLowerCase()
                .replace(" ", "_");

            if (!econItemDefined(itemName))
                continue;
        }
    }
}
